### PR TITLE
Gradle removal

### PR DESCRIPTION
**Pull request by BDHernand**
@rolivieri ok finally got it working.  Take a look

### CODE REVIEW

**Comment by rolivieri** [comment]
Looks good; next steps are:

- Remove `openjdk-7-jdk` from https://github.com/IBM-Swift/kitura-ubuntu-docker/blob/master/Dockerfile.

**Comment by BDHernand** [comment]
@rolivieri why are we removing the cloning of devops.  Does that also mean removing the Kitura-testing-credentials as well or just devops?

**Comment by shmuelk** [comment]
Please do NOT remove the cloning of Kitura-testing-credentials as we in Kitura use for various tests.

In general it would be nice if the Kitura team was told about such changes before they happen as we also use Kitura-Build. In fact it was written for use by Kitura and adopted by others......

**Comment by BDHernand** [comment]
@shmuelk  Oh only DevOps is being removed.

**Comment by rolivieri** [comment]
@BDHernand We are only removing DevOps; we cannot remove Kitura-testing-credentials... that would break a lot of things.

**Pull request merged**
